/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { BsGithub, BsLinkedin } from "react-icons/bs";
import Navbar from "../components/Navbar";
import Card from "../components/Card";
import { CgWebsite } from "react-icons/cg";
import { FaEthereum } from "react-icons/fa";
import { HiOutlineMail } from "react-icons/hi";
import Corousel, { CorouselItem } from "../components/Corousel";
import Skills from "../components/Skills";
export default function Home() {
  const router = useRouter();
  const path = router.pathname;
  console.log(path);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <section className={styles.top} id="home">
          <div className={styles.top_div}>
            <div className={styles.top_left}>
              <span style={{ fontSize: "1.8em" }}>
                Hi, <span style={{ color: "#00BD95" }}>I'm</span>
              </span>{" "}
              <br /> <br />
              <span
                id={styles.name}
                style={{
                  fontSize: "3rem",
                  fontWeight: "bolder",
                  color: "#00BD95",
                }}
              >
                Partik Singh
              </span>
              <br />
              <br />
              <span
                style={{
                  fontSize: "1.2em",
                  fontWeight: "bolder",
                }}
              >
                Full Stacks Web Developer,Blockchain Learner
              </span>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Mollitia laborum quo culpa! Illo quasi nemo odio repellat
                voluptatem quam.
              </p>
              <div className={styles.top_social}>
                Check Out My
                <section className={styles.diamond_section}>
                  <div className={styles.diamond}>
                    <a
                      href="https://github.com/partik03"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <BsGithub style={{ fontSize: "1.5rem" }} />
                    </a>
                  </div>
                  <div className={styles.diamond}>
                    <a
                      href="https://www.linkedin.com/in/partik-singh-945a87227/"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <BsLinkedin />
                    </a>
                  </div>
                  <div className={styles.diamond}>
                    <a href="mailto:partikbumrah13508@gmail.com">
                      <HiOutlineMail />
                    </a>
                  </div>
                </section>
              </div>
            </div>
            <div className={styles.top_right}>
              Right Section
              <img src={"./Partik.jpg"} alt="" />
            </div>
          </div>
        </section>
        <section id="about" className={styles.about}>
          <span
            style={{
              color: "white",
              fontSize: "1.8em",
            }}
          >
            My{" "}
            <span
              style={{
                color: "#00BD95",
              }}
            >
              Services
            </span>
          </span>
          <br />
          <span
            style={{
              fontSize: "4em",
              fontFamily: "monospace",
              color: "white",
              fontWeight: "bolder",
            }}
          >
            What I do
          </span>
          <div className={styles.cards}>
            <Card
              icon={CgWebsite}
              title="Web Development"
              details="Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laborum quo culpa! Illo quasi nemo odio repellat voluptatem quam."
            />
            <Card
              icon={FaEthereum}
              title="BlockChain Development"
              details="Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laborum quo culpa! Illo quasi nemo odio repellat voluptatem quam."
            />
            <Card
              icon={BsGithub}
              title="Web Development"
              details="Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laborum quo culpa! Illo quasi nemo odio repellat voluptatem quam."
            />
          </div>
        </section>
        <section className={styles.projects} id="projects">
          <h2>
            Recent{" "}
            <span
              style={{
                color: "#00CFA1",
              }}
            >
              Projects
            </span>
          </h2>
          <br />
          <span>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat,
            adipisci asperiores facilis mollitia alias quisquam saepe doloribus
            expedita neque cupiditate ratione nulla minus, quos est perspiciatis
            quas minima enim? Voluptatibus.
          </span>
          <Corousel />
        </section>
        <section className={styles.skills}>
          <span
            style={{
              color: "white",
              fontSize: "3em",
            }}
          >
            My{" "}
            <span
              style={{
                color: "#00BD95",
              }}
            >
              Skills
            </span>
          </span>
          <div className={styles.skill_div}>
            <p align="center">
              <Skills/>
            </p>
            <span
            style={{
              color: "white",
              fontSize: "2em",
              position: "absolute",
              bottom: 0,

            }}
        
          >
            Many{" "}
            <span
              style={{
                color: "#00BD95",
              }}
            >
              More  
            </span>
            <t /> to Come ... 
          </span>
          </div>
        </section>
      </main>
    </div>
  );
}
