/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { motion } from "framer-motion";
import { BsGithub, BsLinkedin } from "react-icons/bs";
import Navbar from "../components/Navbar";
import Card from "../components/Card";
import { CgWebsite } from "react-icons/cg";
import { FaEthereum } from "react-icons/fa";
import { HiOutlineMail } from "react-icons/hi";
import Corousel, { CorouselItem } from "../components/Corousel";
import Skills from "../components/Skills";
import Footer from "../components/Footer";
import Typewriter from "typewriter-effect";
import Form from "../components/Form";
import { useMediaQuery } from "../utils/MediaQuery";
export default function Home() {
  const router = useRouter();
  const path = router.pathname;
  console.log(path);
  
  const isSmall = useMediaQuery("(max-width: 768px)");
  return (
    <div className={styles.container}>
      <Head>
        <title>Partik Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <section className={styles.top} id="home">
          <div className={styles.top_div}>
            <motion.div
              // initial={{ opacity: 0, x: 1000 }}
              // animate={{ opacity: 1, x: 0, rotate: [0, 180, 0] }}
              // transition={{
              //   delay: 1,
              //   type: "spring",
              //   stiffness: 120,
              //   bounce: 0.8,
              //   duration: 1,
              // }}
              // dragElastic={0.5}
              className={styles.top_left}
            >
              <span style={{ fontSize: "1.8em" }}>
                Hi, <span style={{ color: "#00BD95" }}>I&apos;m</span>
              </span>{" "}
              <br /> <br />
              
              <span
              // className="anim-typewriter"imsvm
                id={styles.name}
                style={{
                  fontSize: "3rem",
                  fontWeight: "bolder",
                  color: "#00BD95",
                  
                }}
              >
                <Typewriter
                options={{
                  loop: true,

                }}
                 onInit={(typewriter) => {
                  typewriter.typeString('Partik Singh')
                    .callFunction(() => {
                      console.log('String typed out!');
                    })
                    .pauseFor(2500)
                    .deleteAll()
                    .callFunction(() => {
                      console.log('All strings were deleted');
                    })
                    .start();
                }}
              />
               
              </span>
              {/* <br /> */}
              {/* <br /> */}
              <span
                style={{
                  fontSize: "1.2em",
                  fontWeight: "bolder",
                }}
              >
                Full Stacks Web Developer,Blockchain Learner
              </span>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Mollitia laborum quo culpa! Illo quasi nemo odio repellat
                voluptatem quam.
              </p>
              <div className={styles.top_social}>
                Check Out My
                <section className={styles.diamond_section}>
                  <motion.div
                    initial={{ opacity: 0, x: -100 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    transition={{delay:0.5,type:"spring",stiffness:120,bounce:0.8,duration:2}}
                  className={styles.diamond}>
                    <a
                      href="https://github.com/partik03"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <BsGithub style={{ fontSize: "1.5rem" }} />
                    </a>
                  </motion.div>
                  <motion.div
                     initial={{ opacity: 0, y: -100 }}
                     whileInView={{ opacity: 1, y: 0 }}
                     transition={{delay:0.5,type:"spring",stiffness:120,bounce:0.8,duration:2}}
                  className={styles.diamond}>
                    <a
                      href="https://www.linkedin.com/in/partik-singh-945a87227/"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <BsLinkedin />
                    </a>
                  </motion.div>
                  <motion.div 
                  initial={{ opacity: 0, x: 100 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  transition={{delay:0.5,type:"spring",stiffness:120,bounce:0.8,duration:2}}
                  className={styles.diamond}>
                    <a href="mailto:partikbumrah13508@gmail.com">
                      <HiOutlineMail />
                    </a>
                  </motion.div>
                </section>
              </div>
            </motion.div>
            <div className={styles.top_right}>
            <iframe
                src="https://my.spline.design/miniroommusiccopy-de15a1ddd9696d70c5a3da276a73444a/"
                frameBorder="0"
                width="100%"
                height="100%"
              ></iframe>
            </div>
          </div>
        </section>
        <section id="about" className={styles.about}>
          <motion.span
            whileInView={{ opacity: 1, y: 0, rotate: [0, 180, 0] }}
            initial={{ opacity: 0, y: -1000 }}
            style={{
              color: "white",
              fontSize: "1.8em",
            }}
          >
            My{" "}
            <span
              style={{
                color: "#00BD95",
              }}
            >
              Services
            </span>
          </motion.span>
          <br />
          <motion.span
            whileInView={{ opacity: 1, x: 0, rotate: [0, 180, 0] }}
            initial={{ opacity: 0, x: -1000 }}
            style={{
              fontSize: "4em",
              fontFamily: "monospace",
              color: "white",
              fontWeight: "bolder",
            }}
          >
            What I do
          </motion.span>
          <div className={styles.cards}>
            <motion.div
               initial={isSmall?{opacity:0,x:50}:{ opacity: 0, x: 1000 }}
              whileInView={{ opacity: 1, x: 0, rotate: [270, 180, 0] }}
              transition={{
                delay: 0.5,
                type: "spring",
                stiffness: 120,
                bounce: 0.8,
                duration: 1,
                staggerChildren: 3,
              }}
              viewport={{ amount: 0.5 }}
              exit={{ opacity: 0, x: -50 }}
              
            >
              <Card
                icon={CgWebsite}
                title="Web Development"
                details="Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laborum quo culpa! Illo quasi nemo odio repellat voluptatem quam."
              />
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: 100 }}
              whileInView={{ opacity: 1, x: 0, rotate: [270, 180, 0] }}
              transition={{
                delay: 1.5,
                type: "spring",
                stiffness: 120,
                bounce: 0.8,
                duration: 1,
                staggerChildren: 3,
              }}
              viewport={{ amount: 0.5 }}
              exit={{ opacity: 0, x: -50 }}
            >
              <Card
                icon={FaEthereum}
                title="BlockChain Development"
                details="Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laborum quo culpa! Illo quasi nemo odio repellat voluptatem quam."
              />
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: 100 }}
              whileInView={{ opacity: 1, x: 0, rotate: [270, 180, 0] }}
              transition={{
                delay: 2.5,
                type: "spring",
                stiffness: 120,
                bounce: 0.8,
                duration: 1,
                staggerChildren: 3,
            
              }}
              exit={{ opacity: 0, x: -50 }}
              viewport={{ amount: 0.5 }}
            >
              <Card
                icon={BsGithub}
                title="Open Source"
                details="Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laborum quo culpa! Illo quasi nemo odio repellat voluptatem quam."
              />
            </motion.div>
          </div>
        </section>
        <section className={styles.projects} id="projects">
          <h2>
            Recent{" "}
            <span
              style={{
                color: "#00CFA1",
              }}
            >
              Projects
            </span>
          </h2>
          <br />
          <span>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat,
            adipisci asperiores facilis mollitia alias quisquam saepe doloribus
            expedita neque cupiditate ratione nulla minus, quos est perspiciatis
            quas minima enim? Voluptatibus.
          </span>
          <div className="w-full flex justify-center items-center">
          {/* <Corousel /> */}
          </div>
        </section>
        <section className={styles.skills}>
          <span
            style={{
              color: "white",
              fontSize: "3em",
            }}
          >
            My{" "}
            <span
              style={{
                color: "#00BD95",
              }}
            >
              Skills
            </span>
          </span>
          <motion.div
            initial={{ opacity: 0, x: -1000 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ staggerChildren: 2, delayChildren: 2 }}
            viewport={{ amount: 0.2 }}
            className={styles.skill_div}
          >
            <motion.p
              initial={{ opacity: 0, y: 500 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{
                delay: 0.5,
                type: "spring",
                stiffness: 120,
                bounce: 0.8,
                duration: 1,
              }}
              align="center"
            >
              <Skills />
            </motion.p>
            <span
              style={{
                color: "white",
                fontSize: "2em",
                position: "absolute",
                bottom: 0,
              }}
            >
              Many{" "}
              <span
                style={{
                  color: "#00BD95",
                }}
              >
                More
              </span>
              <t /> to Come ...
            </span>
          </motion.div>
        </section>
        <section className="h-screen">
              <Form/>
        </section>
        <section className="h-min">
          <Footer />
        </section>
      </main>
    </div>
  );
}
